select curdate() as data_atual;
select current_date() as data_atual;
select curtime() as horario_atual;
select current_time() as data_atual;
select date_add(current_date(), interval 3 year) as data_vencimento;
select date_sub(current_date(), interval 10 day) as data_de_matricula;
select datediff(current_date(), '2019-04-19') as 'diferenca';
select date_format(curdate(), '%d/%m/%Y') as 'data formatada';
select dayname(current_date()) as "hoje é...";
select dayofmonth(current_date()) as 'dia do mes';
select dayofweek(current_date()) as 'dia da semana';
select dayofyear(current_date()) as 'dia do ano';
select from_days(780500) as 'dia 780500';
select now() as agora;
select date_format(now(), "%d/%m%Y %H:%m:%s") AS "horario atual";
select current_timestamp() as 'agora';
select time(current_timestamp());
select sec_to_time(2000);
select time_to_sec('01:30:10');
select hour('12:45:12') as hora, minute('12:45:12') as minutos, second('12:45:12') as segundos;
select period_diff(202004, 201909) as 'diferenca de meses';
select timediff('12:56:24', '05:32:22');
select quarter("2019-04-23") as trimestre;
select week("2020-09-29") as 'semana do ano';
select weekday("2020-09-29") as 'dia da semana';
select year("2020-09-29") as 'ano';
select month(now()) as 'mes';